server:
  port: 8888

hbase:
  config:
    xml: hbase-config-local.xml

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    root: debug
